// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuhfCi4suFLwFPscaoBJ2BejrMU_f8tqs',
    appId: '1:679095151892:web:bc10c1b9c7689954d0a601',
    messagingSenderId: '679095151892',
    projectId: 'foodscan-app-61fd9',
    authDomain: 'foodscan-app-61fd9.firebaseapp.com',
    storageBucket: 'foodscan-app-61fd9.firebasestorage.app',
    measurementId: 'G-E29G8PT93N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU3qnLkKYp94veCjARpSjZSf6w0nys2ug',
    appId: '1:679095151892:android:a7f8b6a3caf4237dd0a601',
    messagingSenderId: '679095151892',
    projectId: 'foodscan-app-61fd9',
    storageBucket: 'foodscan-app-61fd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLdUrMmtZxujW-npXHS6guWTIkAQUkca0',
    appId: '1:679095151892:ios:c57f705120bc746dd0a601',
    messagingSenderId: '679095151892',
    projectId: 'foodscan-app-61fd9',
    storageBucket: 'foodscan-app-61fd9.firebasestorage.app',
    iosBundleId: 'com.example.main',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLdUrMmtZxujW-npXHS6guWTIkAQUkca0',
    appId: '1:679095151892:ios:c57f705120bc746dd0a601',
    messagingSenderId: '679095151892',
    projectId: 'foodscan-app-61fd9',
    storageBucket: 'foodscan-app-61fd9.firebasestorage.app',
    iosBundleId: 'com.example.main',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuhfCi4suFLwFPscaoBJ2BejrMU_f8tqs',
    appId: '1:679095151892:web:1809378b3b93c2d4d0a601',
    messagingSenderId: '679095151892',
    projectId: 'foodscan-app-61fd9',
    authDomain: 'foodscan-app-61fd9.firebaseapp.com',
    storageBucket: 'foodscan-app-61fd9.firebasestorage.app',
    measurementId: 'G-VTPMJ8M33C',
  );
}
